#!/usr/bin/env python3
"""Generate a manual Python compile-stress fixture for Rimera Lite."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import subprocess
import tempfile
import time


def source_for(statement_count: int) -> str:
    lines = [
        "# Generated by scripts/generate_compile_stress.py.",
        "# This fixture is intentionally large; do not commit it.",
        "value = 0",
    ]
    lines.extend(f"value = value + {index % 97}" for index in range(statement_count))
    lines.append("print(value)")
    return "\n".join(lines) + "\n"


def compile_sample(rimera: Path, source: Path) -> float:
    with tempfile.TemporaryDirectory(prefix="rimera-stress-") as temporary:
        output = Path(temporary) / "sample"
        environment = os.environ | {"RIMERA_COLOR": "never"}
        started = time.monotonic()
        completed = subprocess.run(
            [str(rimera), "build", str(source), "--output", str(output)],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            env=environment,
        )
        elapsed = time.monotonic() - started
    if completed.returncode != 0:
        raise RuntimeError("the calibration build failed")
    return elapsed


def main() -> None:
    repository = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target-seconds",
        type=float,
        default=20.0,
        help="approximate duration of the final compile on this machine (default: 20)",
    )
    parser.add_argument(
        "--sample-statements",
        type=int,
        default=2_000,
        help="number of operations used for the calibration build (default: 2000)",
    )
    parser.add_argument(
        "--max-statements",
        type=int,
        default=500_000,
        help="safety cap for the generated program (default: 500000)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repository / "tests/fixtures/stress/compile_stress.py",
        help="generated Python source path",
    )
    parser.add_argument(
        "--rimera",
        type=Path,
        default=repository / "target/debug/rimera",
        help="built Rimera Lite executable used for calibration",
    )
    arguments = parser.parse_args()

    if arguments.target_seconds <= 0:
        parser.error("--target-seconds must be positive")
    if arguments.sample_statements <= 0:
        parser.error("--sample-statements must be positive")
    if not arguments.rimera.is_file():
        parser.error(f"Rimera Lite executable was not found: {arguments.rimera}")

    with tempfile.TemporaryDirectory(prefix="rimera-stress-source-") as temporary:
        sample = Path(temporary) / "sample.py"
        sample.write_text(source_for(arguments.sample_statements), encoding="utf-8")
        elapsed = compile_sample(arguments.rimera, sample)

    estimated = round(arguments.sample_statements * arguments.target_seconds / elapsed)
    statement_count = min(max(arguments.sample_statements, estimated), arguments.max_statements)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(source_for(statement_count), encoding="utf-8")
    print(
        f"generated {arguments.output} with {statement_count:,} operations "
        f"(calibration: {elapsed:.2f}s for {arguments.sample_statements:,})"
    )


if __name__ == "__main__":
    main()
